name: Auto Update AQI Data

on:
  schedule:
    - cron: "0 * * * *"   # runs every hour
  workflow_dispatch:       # manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write      # ✅ allow pushing to repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch latest AQI data
        run: python scripts/fetch_hourly_historical_data.py

      - name: Train & predict AQI
        run: python scripts/predict_aqi.py

      - name: Commit updated data & predictions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/ predictions/
          git commit -m "Auto-update AQI data & predictions [skip ci]" || echo "No changes to commit"
          git push
