name: Update AQI Data and Retrain Models

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:      # allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch latest AQI data
        run: python scripts/fetch_hourly_historical_data.py

      - name: Retrain models
        run: python scripts/train_models.py

      - name: Predict next 3 days
        run: python scripts/predict_aqi.py

      - name: Commit updated data & predictions
  run: |
     git config --global user.name "github-actions[bot]"
     git config --global user.email "github-actions[bot]@users.noreply.github.com"
     git add data/ predictions/
     git commit -m "Auto-update AQI data & predictions [skip ci]" || echo "No changes to commit"
     git push
    env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

